name: Java Integration Tests

on: [push, pull_request]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration Tests

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: zulu
      - name: Integration Test with Maven
        run: ./mvnw -B -V -DtestSrc=remote -Prun-its verify -Dinvoker.parallelThreads=8 -Dlicense.skip=true --no-transfer-progress
