name: Java Integration Tests

on: [push, pull_request]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 30
    name: Integration Tests

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
        with:
          cache: maven
          distribution: zulu
          java-version: 21
      - name: Integration Test with Maven
        run: ./mvnw --batch-mode --show-version -DtestSrc=remote -Prun-its verify -Dinvoker.parallelThreads=8 -Dlicense.skip=true --no-transfer-progress
